language: node_js
node_js:
- '0.11'
addons:
  code_climate:
    repo_token: 19b2bef0d558342efbe289f07a9b415d3dd1cdb88bf2d2770a85402b98ffdee6
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
